export const lightTheme = {
  mode: "light",
  background: "#F5F6F8",
  borderColor: "#EDF0F4",
  text: "#3D4F64",
  textClear: "#FFFFFF",
  primary: "#061D3D",
  accent: "#FF8000",
  buttonBackground: "#FF8000",
  buttonText: "#FFFFFF",
  backgroundCard: "#FFFFFF",
  backgroundCardBlue: "#061D3D",
  initialsCircle: "#061D3D",
  statusBarStyle: "#061D3D" as const,
};
