export const lightTheme = {
  mode: "light",
  background: "#F5F6F8",
  borderColor: "#EDF0F4",
  text: "#3D4F64",
  textClear: "#FFFFFF",
  primary: "#FF8000",
  accent: "#061D3D",
  buttonBackground: "#FF8000",
  buttonText: "#FFFFFF",
  backgroundCard: "#FFFFFF",
  backgroundCardBlue: "#FF8000",
  initialsCircle: "#FF8000",
  statusBarStyle: "#FF8000" as const,
};
